- lua/dapui/elements/watches.lua
This lets users use omni-completion to complete variable names within
the watches buffer.
This also works together with the `autocompl` extension in dap, so users
could add a `dapui_watches.vim` in `ftplugin` with:
lua require('dap.ext.autocompl').attach()
And it would automatically trigger the omnifunction on the
signatureTrigger characters (usually `.`)
Nice work so far :)
> Set omnifunc to dap.omnifunc in watches buffer

- lua/dapui/elements/stacks.lua
According to the specification `source` in frame is optional.
(With the java debugger I got native frames in the response that have no source)
I'm not too happy with the `NO SOURCE` fallback, it's the first thing that came
to mind. Maybe you've a better idea.
> Handle nil frame.source in stacks

- README.md
You probably meant to show case the default values for `elements` in the README.
> Use `"stacks"` in README example

- README.md
Fix default config docs syntax error
> docs: fix default config syntax error

- README.md
- lua/dapui/config/init.lua
- lua/dapui/windows/float.lua
Hi, I've added an option to set the border style of floating windows
+ ![single](https://user-images.githubusercontent.com/76592799/140338869-4c0547b9-8a38-48df-bf44-d0adc3573758.png)
+ ![double](https://user-images.githubusercontent.com/76592799/140338910-212ebcff-5dd9-46d6-a571-5eff569bc1f8.png)
+ ![rounded](https://user-images.githubusercontent.com/76592799/140338945-cc5a7bad-2007-42e5-af0b-4c67a396b237.png)
> added border style option

- README.md
- lua/dapui/windows/init.lua
- lua/dapui/windows/layout.lua
Allows float numbers to be passed in **size** argument to use as percentage of a
window width/height.
With this pr, and using config presented below, you can always perfectly align bottom and side layout sections (_matched sections colored orange_):
```lua
layouts = {
{
elements = {
{ id='breakpoints', size=0.30 }, -- Match this value
{ id='scopes',      size=0.45 },
{ id='watches',     size=0.25 },
},
size = 0.30,
position = 'left',
},
{
elements = { 'repl' },
size = 0.30 -- With this value,
position = 'bottom',
},
},
```
> Allow float numbers in size configuration

- lua/dapui/render/line_hover.lua
- lua/dapui/windows/init.lua
When I trigger float window when the content is empty it trigger error.
These are the changes I make to prevent it from happening.
> fix(float): prevent error when opening empty float.

- lua/dapui/config/init.lua
- lua/dapui/init.lua
- lua/dapui/render/canvas.lua
- lua/dapui/state.lua
- lua/dapui/util.lua
- lua/dapui/windows/init.lua
Some notification alternative plugins enforce `vim.notify`'s expected type for its log level argument. So, we've replaced the string representations in this plugins to use the `vim.log.levels` enum representation instead.
> fix: use vim.log.level enums for vim.notify lvls

- lua/dapui/init.lua
This allows to use the controls on anothers plugins, just using `require("dapui").controls()` and setting display controls element as empty, so the setup is made by the status line plugin.
This is how will look on the plugin that I maintain ([neoline.vim](https://github.com/adelarsq/neoline.vim)):
@rcarriga Can you take a look?
> fix: ignore setup if config.controls.element is empty

- lua/dapui/config/highlights.lua
Without a background the control icons leave ugly "gaps" inside the window bar. This PR makes it so that the highlight groups are patches with the current value of `WinBar` or `WinBarNC`, depending on whether the window is current or not. Autocommands are set up to re-patch the background every time the user enters of leaves the window.
(green background intentionally exaggerated)
This assumes that the control icons are only in the REPL window. I don't know how we could handle the situation where a user has the control icons on more than one window. Supposed the user has control icons on the REPL and breakpoints window. If he leaves or enters the REPL the highlight groups are patched and the background flips in the breakpoints window as well because both share the same highlight groups.
I …
> Patch control highlight groups with background

- lua/dapui/config/highlights.lua
- lua/dapui/init.lua
This is the continuation of #174, it fixes the remaining issue I mentioned over there. Now the background should work regardless of which window carries the control UI. I wish Vim's highlight system had a sort of "inheritance" feature that is between `link` and defining from scratch. Then we would not have to do this ugly highlight group patching.
For each of the control highlight groups there is now a corresponding highlight group with the same name plus `NC` as suffix. When entering or exiting the window which carries the support groups we reset the 'winbar' option such that the highlight groups are either normal or `*NC`.
The reason for this is that the user might have a different background for the highlight groups `WinBar` and `WinBarNC`. Whenever the user exits or enters a window, …
> Implement separate *NC control highlight groups

- README.md
By accident in #179 PR I duplicated links in readme file. This one fixes it
> docs(README): fix link destination

- lua/dapui/config/highlights.lua
> fixed highlighting for neovim 0.8+

- README.md
- lua/dapui/windows/init.lua
Should solve #202 . 
Or better to make like `nui.nvim`? Which have `position` and `relative` option. More on [there](https://github.com/MunifTanjim/nui.nvim/tree/main/lua/nui/popup)
> Add center option to float

- lua/dapui/components/frames.lua
- lua/dapui/components/scopes.lua
Hello, I've encountered the following issue:
Whenever im pressing step_over() really fast, I get the following error message:
```
Rendering failed: ...re/nvim/lazy/nvim-dap-ui/lua/dapui/components/frames.lua:28: attempt to index field 'session' (a nil value)
stack traceback:
...io/.local/share/nvim/lazy/nvim-dap-ui/lua/dapui/util.lua:17: in function '__index'
...re/nvim/lazy/nvim-dap-ui/lua/dapui/components/frames.lua:28: in function 'render'
...e/nvim/lazy/nvim-dap-ui/lua/dapui/components/threads.lua:45: in function 'render_thread'
...e/nvim/lazy/nvim-dap-ui/lua/dapui/components/threads.lua:68: in function 'render'
...hare/nvim/lazy/nvim-dap-ui/lua/dapui/elements/stacks.lua:27: in function 'render'
...hare/nvim/lazy/nvim-dap-ui/lua/dapui/elements/stacks.lua:19: in function …
```
> add checks if data is accessible

- README.md
I really like this plugin but found it a little difficult to get started. I have a suggestion here which I think is important: the README does not actually define what a "Mapping" is or describe how to activate them, and it required reading a lot of the details of the docs for me to understand. I think the main README should have a minimal self-contained description of how to actually use the bindings in the plugin, and I added a short description. I also took the liberty of moving the discussion on some recommended dependencies into the "Installation" section.
> Add default mapping keybindings to README

- lua/dapui/config/highlights.lua
**Context**
Highlight groups set by colorschemes are overwritten by `nvim-dap-ui` plugin in the `require("dapui.config").highlights.lua:setup()` method, instead of just setting the fallback *default* highlight groups.
More information can be found in #275 and #178.
---
**Changes**
1. Modified the method to set the defaults for highlight groups instead of overwriting previously set highlights.
2. Cleaned up the `setup()` method logic by moving the error checking (`pcall`) into the helper function. 
3. Added a helper function to use the newer `nvim_get_hl` API function if NeoVim's version is atleast 0.9.
> fix(#275): do not overwrite colorscheme highlights

- lua/dapui/render/line_hover.lua
- lua/dapui/windows/layout.lua
So as to not clobber other custom window highlights.
I highlight `NormalNC` to dim the other windows that are not focused, and for the exceptions I append `NormalNC:NONE` to `winhighlight`. `nvim-dap-ui` windows are such cases (to wit, windows with special buffers, i.e., `buftype` is not empty), but the plugin overwrites that.
I propose using `vim.opt` and override only what is necessary to deliver the desired look and feel, while preserving other highlights.
> Using vim.opt.winhighlight:append

- lua/dapui/util.lua
If you have a keymap for `qq`, then pressing `q` will result in a small delay, since vim waits to see whether you are pressing `q` or `qq`.
This PR fixes the issue by adding [nowait](https://neovim.io/doc/user/map.html#%3Amap-nowait) to the keymaps on creation.
> fix: delay for keymaps

- README.md
The event_initialized used previously will sometimes fire despite debugging not being able to start.
For me this is reproducible by pressing ESC on the prompt for a debugee binary path with codelldb.
> docs(README): improve suggested listener setup

- lua/dapui/windows/float.lua
It looks like in https://github.com/rcarriga/nvim-dap-ui/commit/d7a9f032e7e45b37d778ef83e3d412566ba97cb5, the use of `DapUIFloatNormal` was introduced, but two different names were used (`DapUIFloatNormal` and `DapUINormalFloat`).
This fix is correcting the names to both be `DapUIFloatNormal` as it seems to follow the general naming convention used
> fix(highlights): Correct DapUINormalFloat to DapUIFloatNormal

- lua/dapui/init.lua
> fix(eval): open the floating window under the cursor

- lua/dapui/components/variables.lua
fixes issue https://github.com/rcarriga/nvim-dap-ui/issues/325
---
`prompt_func` is not being reset to `nil` when editing a variable. This causes `canvas:set_prompt()` to get trigger on every other action, like `expand`.
> fix: make sure to clear prompt_func after editing variable

- lua/dapui/init.lua
- lua/dapui/windows/float.lua
- lua/dapui/windows/init.lua
It's useful when opening a window that contains nothing to distinguish elements.
I can add an option to opt for that if needed.
> feat(float_element): show name of float element as window title

- lua/dapui/logging.lua
- scripts/gendocs.lua
Deprecation warnings in v0.10 and v11 nightlies
```
vim.tbl_flatten is deprecated, use vim.iter(…):flatten():totable() instead. :help deprecated
Feature will be removed in Nvim 0.12
```
> fix: replace tbl_flatten to flatten():totable()

- lua/dapui/logging.lua
- lua/dapui/util.lua
- scripts/gendocs.lua
Add compatible tbl_flatten to fix #360.
This is similar to the implementation in nvim-lspconfig.
> fix: add compatible tbl_flatten

- lua/dapui/init.lua
Often, when opening and closing the UI, the output window gets progressively smaller.
This seems to be caused by the second call to win_layout:update_sizes detecting different total width for the bottom panel in the default configuration.
If the vertical layout has already been closed, the command windows is resized (by vim, not much that can be done in that case) and the win_size computation is incorrect. The next time dapui is opened the command window has a larger percentage of the layout.
The fix seems to be updating the sizes before closing any layout, which as far as I understand is already done few lines above.
I have tested it with my configuration, but if there is any edge case (in particular with args) I'd be happy to revisit this PR.
> Fix output window incorrectly resizing

- lua/dapui/client/lib.lua
Fixes #349
As reported by the linked issue, editing variables shows an error, although it works as expected. The problem was that it wasn't capturing the first `pcall` return value (aka success) to figure out whether the `pcall` worked or not, and then, yes, use its second return value (aka `result`) to eventually handle the error.
More info: http://www.lua.org/manual/5.1/manual.html#pdf-pcall
> Fix edit variables

- lua/dapui/components/scopes.lua
- tests/unit/elements/scopes_spec.lua
Currently, the "Scopes" widget renders all variables for every scope. However, this can become problematic when dealing with large global scopes, particularly when importing frameworks like React. This results in noticeable performance degradation, as mentioned in [this Reddit post I made](https://www.reddit.com/r/neovim/comments/1foy8fp/why_is_js_neovim_debugger_so_slow_compared_with/).
To address this issue, I’ve made the "Scopes" widget expandable. When a scope is collapsed, it is not rendered, thereby improving performance. Additionally, I’ve utilized the `expensive` flag from the [Debugger Adapter Protocol `Scope` type](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Scope) to automatically collapse scopes that are too resource-intensive to render.
Users can …
> Fix performance issues by allowing Scopes to be disabled

- doc/nvim-dap-ui.txt
- lua/dapui/init.lua
Add documentation for the floating window param introduced in #215 
After seeing a mention that the docs were not modified manually but rather generated with I script, I added the field to the class and generated the docs using the script provided in scripts/docgen
> Add documentation for floating window position param

- lua/dapui/init.lua
Fix Float Element Can Be Open While There Is No dap Session Alive #398 
This fix will detect debug session before opening a float element when executing `require("dapui").float_element()`. If there is no debug session found it will stop execution and prompt a warning "No active debug session"
> fix(dapui): opening float element requires a debug session

- lua/dapui/windows/layout.lua
in some cases win_size is nil, which makes the round thrown an error
fixes #405
> guarantees that win_size won't be nil (#405)

- lua/dapui/windows/float.lua
- lua/dapui/windows/init.lua
When trying to open float element with `position="center"` but without `width` and `height` provided
```lua
require('dapui').float_element('breakpoints', {position='center'})
```
the float element is not opened and throws error which says that `settings.height` used in calculations is actually a `nil` value. 
<details><summary>Traceback</summary>
<p>
```
msg_show.lua_error Error executing vim.schedule lua callback: .../.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:100: Async task failed without callback: The coroutine failed with this message: 
...l/share/nvim/lazy/nvim-dap-ui/lua/dapui/windows/init.lua:129: attempt to perform arithmetic on field 'height' (a nil value)
stack traceback:
...l/share/nvim/lazy/nvim-dap-ui/lua/dapui/windows/init.lua: in function 'open_float' …
```
> fix(float_element): auto detect size for centered floating element

- lua/dapui/components/frames.lua
Fixes: https://github.com/rcarriga/nvim-dap-ui/issues/387 (see this issue for more context) 
Request thread stack trace in case Debug Adapter hasn't reported it. This makes it possible to see stack traces for every thread when debugging multi-threaded application, which apparently was broken for around half a year due to regression introduced by: https://github.com/rcarriga/nvim-dap-ui/commit/a62e86b124a94ad1f34a3f936ea146d00aa096d1
Asking each thread for a stack trace can be a bit slow though (depending on adapter/debugger and project size). For example when debugging something like Unreal Engine Editor which is huge and runs with around 50+ threads, the difference in response times is noticeable. **It would be nice to have an option for disabling this feature. I can add it right after …
> fix: request thread stack trace if client hasn't reported it

- doc/nvim-dap-ui.txt
- lua/dapui/elements/breakpoints.lua
- lua/dapui/elements/watches.lua
- lua/dapui/init.lua
[#339 ](https://github.com/rcarriga/nvim-dap-ui/pull/399) forbids floating all elements without an active debug session. But using `breakpoints` and `watches` elements makes perfect sense in-between sessions (i.e. jumping/toggling/removing breakpoints, adding/editing watches), and it breaks such use cases.
This adds `allow_without_session` option to Element, sets it for `breakpoints` and `watches` built-in elements, and limits the introduced behavior to the elements with said option unset.
> fix(dapui): allow certain elements to float without active session

- README.md
see this [issue](https://github.com/rcarriga/nvim-dap-ui/issues/367)
> Update README.md to use lazydev.nvim instead of neodev.nvim

- lua/dapui/render/canvas.lua
- lua/dapui/util.lua
Allow a user to use `map <buffer>` in a dapui buffer to see what the mappings do.
We already have descriptions for these mappings, so pass that through to the mapping definition. This also makes it easier for a user to know the names they need to use to change the keys bound to these mappings -- the strings are the keys used in mapping configuration.
Output of `:map <buffer>`:
> Add a description to mappings

- lua/dapui/render/line_hover.lua
Neovim v0.11 added `winborder` option that specifies border style of every float window that hasnt overriden it.
In order to preserve "no borders" look of `line_hover`, we have to set border style to `none`.
|before|after|
|-|-|
|![image](https://github.com/user-attachments/assets/ab4e1142-7024-4145-be67-09ab1fbfb43a)|![image](https://github.com/user-attachments/assets/2cfcc938-3b81-4449-9092-55fe7b84cfab)|
> fix: nvim 0.11 overrides float border with default option if not set

- lua/dapui/util.lua
stylua-action failed from my last pr. adjust style to match.
I ran this and it seems to be what it wants:
```vimscript
:exec "!" g:ale_lua_stylua_executable "-f ../../stylua.toml"  expand("%")
```
> lint: Fix style to match stylua

- lua/dapui/components/breakpoints.lua
nvim-dap added handling of breakpoint event ([ea82027](https://github.com/mfussenegger/nvim-dap/commit/ea82027)).
This is simple fix, so that breakpoints window is updated as well.
> Refresh breakpoints window after breakpoint event
